source 'https://github.com/CocoaPods/Specs.git'

#use_frameworks!

platform :ios, '8.0'

target 'YQJRUIKit_Example' do
  pod 'YQJRUIKit', :path => '../'

  target 'YQJRUIKit_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 8.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
      end
    end
  end
end
